apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmctl-celery-worker
  namespace: llmctl
spec:
  template:
    spec:
      containers:
        - name: celery-worker
          image: 10.107.62.134:80/llmctl/llmctl-celery-worker:0.0.1@sha256:4c0f8f885f1cfb0529fcc813aea3480023d1761ea0a4b13a1a560ddbd07c16bf
          command:
            - python3
            - app/llmctl-celery-worker/run.py
            - worker
            - --concurrency
            - "1"
            - --queues
            - llmctl_studio,llmctl_studio.downloads.huggingface,llmctl_studio.rag.index,llmctl_studio.rag.drive,llmctl_studio.rag.git
            - --loglevel
            - info
            - --hostname
            - llmctl-celery-worker@%h
          volumeMounts:
            - $patch: replace
            - name: celery-worker-project-code
              mountPath: /app
            - name: studio-data
              mountPath: /app/data
      volumes:
        - $patch: replace
        - name: celery-worker-project-code
          hostPath:
            path: /workspace/llmctl
            type: Directory
        - name: studio-data
          persistentVolumeClaim:
            claimName: llmctl-studio-data
