apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmctl-celery-beat
  namespace: llmctl
spec:
  template:
    spec:
      containers:
        - name: celery-beat
          image: 10.107.62.134:80/llmctl/llmctl-celery-worker:latest@sha256:4c0f8f885f1cfb0529fcc813aea3480023d1761ea0a4b13a1a560ddbd07c16bf
          command:
            - python3
            - app/llmctl-celery-worker/run.py
            - beat
            - --loglevel
            - info
          volumeMounts:
            - $patch: replace
            - name: celery-beat-project-code
              mountPath: /app
            - name: studio-data
              mountPath: /app/data
      volumes:
        - $patch: replace
        - name: celery-beat-project-code
          hostPath:
            path: /workspace/llmctl
            type: Directory
        - name: studio-data
          persistentVolumeClaim:
            claimName: llmctl-studio-data
