apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmctl-mcp
  namespace: llmctl
spec:
  template:
    spec:
      containers:
        - name: llmctl-mcp
          image: 10.107.62.134:80/llmctl/llmctl-mcp:latest@sha256:3783bf38d06fa9244d5c69cd82cf516ad199ab2504f846d289f61c6838b7a2c3
          command:
            - python3
            - app/llmctl-mcp/run.py
          volumeMounts:
            - name: mcp-project-code
              mountPath: /app
      volumes:
        - name: mcp-project-code
          hostPath:
            path: /workspace/llmctl
            type: Directory
