apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmctl-studio-backend
  namespace: llmctl
spec:
  template:
    spec:
      containers:
        - name: studio
          image: 10.107.62.134:80/llmctl/llmctl-studio-backend:0.0.2@sha256:f026b525b0674b8b6a6f1e39691f6b3c68f515136e3502002cd064c450fd33a8
          command:
            - python3
            - app/llmctl-studio-backend/run.py
          volumeMounts:
            - $patch: replace
            - name: studio-project-code
              mountPath: /app
            - name: studio-data
              mountPath: /app/data
      volumes:
        - $patch: replace
        - name: studio-project-code
          hostPath:
            path: /workspace/llmctl
            type: Directory
        - name: studio-data
          persistentVolumeClaim:
            claimName: llmctl-studio-data
