apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - redis.yaml
  - studio-configmap.yaml
  - studio-pvc.yaml
  - studio-rbac.yaml
  - studio-deployment.yaml
  - studio-service.yaml
