apiVersion: v1
kind: Secret
metadata:
  name: llmctl-pgadmin-secrets
  namespace: llmctl
type: Opaque
stringData:
  PGADMIN_DEFAULT_EMAIL: "admin@example.com"
  PGADMIN_DEFAULT_PASSWORD: "replace-me"
