apiVersion: v1
kind: Service
metadata:
  name: llmctl-studio
  namespace: llmctl
spec:
  type: NodePort
  selector:
    app: llmctl-studio
  ports:
    - name: http
      port: 5155
      targetPort: http
      nodePort: 30155
